version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: rust-toolchain
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/versions/cargo-auditable"
  allow:
  - dependency-name: "cargo-auditable"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/versions/wasmtime/stable"
  allow:
  - dependency-name: "wasmtime-cli"
    update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/versions/wasmtime/stable-1"
  allow:
  - dependency-name: "wasmtime-cli"
    update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/versions/wasmtime/lts"
  allow:
  - dependency-name: "wasmtime-cli"
    update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/versions/wasmtime/lts-1"
  allow:
  - dependency-name: "wasmtime-cli"
    update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  schedule:
    interval: daily

