name: Publish dev

on:
  schedule:
  - cron: "51 * * * *"
  workflow_dispatch:
    inputs:
      git-ref:
        description: git-ref version to build
        type: string
        default: ref/tags/dev

jobs:

  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    outputs:
      rust-version: ${{ steps.versions.outputs.rust-version }}
      git-sha: ${{ steps.versions.outputs.git-sha }}
      git-sha-short: ${{ steps.versions.outputs.git-sha-short }}
      git-date: ${{ steps.versions.outputs.git-date }}
    steps:
    - uses: actions/checkout@v6
    - name: Resolve versions
      id: versions
      run: |
        set -euo pipefail

        echo "rust-version=$(yq -r '.toolchain.channel' rust-toolchain.toml)" | tee -a "${GITHUB_OUTPUT}"

        git_commit=$(gh api repos/bytecodealliance/wasmtime/commits/${{ inputs.git-ref || 'ref/tags/dev' }} --template '{{.sha}} {{.commit.committer.date}}')
        git_sha="$(echo "${git_commit}" | cut -d' ' -f1)"
        git_date="$(echo "${git_commit}" | cut -d' ' -f2)"
        echo "git-sha=${git_sha}" | tee -a "${GITHUB_OUTPUT}"
        echo "git-sha-short=${git_sha:0:7}" | tee -a "${GITHUB_OUTPUT}"
        echo "git-date=${git_date:0:10}" | tee -a "${GITHUB_OUTPUT}"
      env:
        GH_TOKEN: ${{ github.token }}

  build:
    name: Build
    permissions:
      contents: write
      packages: write
    needs: preflight
    uses: ./.github/workflows/publish.yaml
    with:
      rust-version: "${{ needs.preflight.outputs.rust-version }}"
      wasmtime-git-sha: ${{ needs.preflight.outputs.git-sha }}
      repository: dev
      tag: dev-${{ needs.preflight.outputs.git-sha }}
      additional-tags: |
        dev-${{ needs.preflight.outputs.git-sha-short }}
        dev-${{ needs.preflight.outputs.git-date }}
        dev
        latest
    secrets: inherit

  done:
    # used as a non-matrix job for protected branches
    name: Done
    needs: build
    if: always() && (needs.build.result == 'success' || needs.build.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
    - run: echo "That's all folks"
