name: Push

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  schedule:
  - cron: "51 * * * *"

jobs:

  release:
    name: Release
    permissions:
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-releases.yaml
    secrets: inherit

  dev:
    name: Dev
    permissions:
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-dev.yaml
    secrets: inherit
